### ISSUE TITLE
Infill is not generated

### ISSUE THREAD

**Issue by Evil-Spirit** [gradientspace/gsSlicer#1]
When I using the attched example, all the fine
```
        CappedCylinderGenerator cylgen = new CappedCylinderGenerator() {
            BaseRadius = 10, TopRadius = 5, Height = 20, Slices = 32
        };
        DMesh3 mesh = cylgen.Generate().MakeDMesh();
        MeshTransforms.ConvertYUpToZUp(mesh);       // g3 meshes are usually Y-up
```

![gcode viewer - online gcode viewer and analyzer in your browser - google chrome 2018-05-22 21 06 59](https://user-images.githubusercontent.com/1980537/40367646-1c8d1b26-5e04-11e8-9558-166a35996b78.png)

Attempt to generate gcode for this mesh:

![unity 2017 3 0f3 personal 64bit - notecam unity - notecad - pc mac linux standalone _dx11_ 2018-05-22 22 01 56](https://user-images.githubusercontent.com/1980537/40371043-d356da02-5e0b-11e8-87cb-1194a2486f01.png)

Converted from unity mesh by using this function:
```
	public static DMesh3 ToDMesh3(this Mesh mesh) {
		DMesh3 result = new DMesh3();
		result.BeginUnsafeTrianglesInsert();

		var indices = mesh.GetIndices(0);
		var polygons = new List<Polygon>();
		var verts = mesh.vertices;
		for(int i = 0; i < indices.Length / 3; i++) {
			var v0 = verts[indices[i * 3 + 0]];
			var v1 = verts[indices[i * 3 + 1]];
			var v2 = verts[indices[i * 3 + 2]];
			result.AppendTriangle(
				result.AppendVertex(new Vector3d(v0.x, v0.y, v0.z)),
				result.AppendVertex(new Vector3d(v1.x, v1.y, v1.z)),
				result.AppendVertex(new Vector3d(v2.x, v2.y, v2.z))
			);
		}
		result.EndUnsafeTrianglesInsert();
		return result;
	}
```

Resulted in gcode that have no any infill:

![gcode viewer - online gcode viewer and analyzer in your browser - google chrome 2018-05-22 22 04 32](https://user-images.githubusercontent.com/1980537/40371196-215910a8-5e0c-11e8-93a5-2e4a6b1c7ec9.png)

STL is watertight.
What I am doing in wrong way?

**Comment by Evil-Spirit** [comment]
[NoteCADExport.zip](https://github.com/gradientspace/gsSlicer/files/2027282/NoteCADExport.zip)

**Comment by rms80** [comment]
It works for me when I import your STL. My guess is that the unity Mesh you are starting with is not topologically closed, ie it has open boundary loops between the faces. Although it may be geometrically closed, the MeshPlanarSlicer will interpret such a mesh as being a set of separate 'open' sheets, and only pass their outlines to the toolpather. 

So, you need to merge the boundary vertices. A quick-and-dirty way to do that would just be to write out and re-open the STL. You can do this all in memory with StandardMeshReader / StandardMeshWriter, they can take Streams instead of filenames. 

Alternately you could try to hack MeshPlanarSlicer to chain the 2D polylines, eg by matching open polyline endpoints. Naive methods will work in this simple case, but it is extremely difficult to get right in arbitrary cases, eg like meshes with overlapping edges, etc.

![image](https://user-images.githubusercontent.com/2845837/40372774-66f6c640-5db3-11e8-85ac-aa30f1f527de.png)

**Comment by Evil-Spirit** [comment]
@rms80 Thank you for your answer!

**Comment by rms80** [comment]
check DMesh3.IsClosed(). if it returns false, there are boundary edges in the mesh, and that would be why the slicer leaves it open.

**Comment by Evil-Spirit** [comment]
got it! thank you!

**Comment by Evil-Spirit** [comment]
@rms80 btw managed to work slicer online! http://notecam.xyz

**Comment by Evil-Spirit** [comment]
sorry, I don't say - only text stl files supported. And I haven't released new version - so, only simple files not cause memory errors. A little bit later I will send you screenshot.

**Comment by Evil-Spirit** [comment]
![notecam 3d prining helper tool - google chrome 2018-06-05 04 46 28](https://user-images.githubusercontent.com/1980537/40943487-82396520-687b-11e8-9c8d-8846b456b9a0.png)
![gcode viewer - online gcode viewer and analyzer in your browser - google chrome 2018-06-05 04 47 55](https://user-images.githubusercontent.com/1980537/40943522-a327422a-687b-11e8-9a9e-36cadce38645.png)
[escher_export.zip](https://github.com/gradientspace/gsSlicer/files/2070087/escher_export.zip)

**Comment by Evil-Spirit** [comment]
@rms80 I finally solve all the issues!
Now you can try loading any stl files, memory problems should be rare (for simple input files)

Files like this processed with no problems

![notecad 3d modelling tool - google chrome 2018-06-06 04 58 23](https://user-images.githubusercontent.com/1980537/41005079-48c95bee-6946-11e8-9c2d-6e75003c2b97.png)

![notecam 3d prining helper tool - google chrome 2018-06-06 05 03 01](https://user-images.githubusercontent.com/1980537/41005262-ec755176-6946-11e8-80de-786c51c405a3.png)

you can try it yourself: ImportSTL->Slice->GCode

[stlFiles.zip](https://github.com/gradientspace/gsSlicer/files/2074152/stlFiles.zip)

I think it is first true-online slicer, isn't it?

**Comment by rms80** [comment]
These guys have compiled a C++ slicer to javascript: http://shapeforge.loria.fr/slicecrafter/

I can load the files but nothing happens when I click slice (I do not see the toolbar you screenshotted above)
![image](https://user-images.githubusercontent.com/2845837/41006127-49aeec2a-68ee-11e8-9206-3876ea491faa.png)
